### ISSUE TITLE
how to use MAX_POSITION

### ISSUE THREAD

**Issue by Krisa** [binance-exchange/binance-api-postman#10]
As per the release note of March 24th, there is a new parameter, which looks very useful https://binance-docs.github.io/apidocs/spot/en/#change-log. However it cannot be in the ExchangeInfo endpoint as it would need an authenticate call to retrieve the client order. Could you update the collection to demonstrate which endpoint returns this value?

**Comment by 2pd** [comment]
It's not released in production yet. After it's enabled, there is no need to update the collection, exchangeInfo endpoint will return it instantly.
