### ISSUE TITLE
Signature error on margin query

### ISSUE THREAD

**Issue by kirosc** [binance-exchange/binance-api-postman#13]
Getting error on some margin order queries.
```
{
    "code": -1022,
    "msg": "Signature for this request is not valid."
}
```

**Comment by 2pd** [comment]
Please make sure you have checked with this:
https://github.com/binance-exchange/binance-api-postman#error-signature-for-this-request-is-not-valid

Otherwise please paste your request raw, hide the signature for your saftely.
