### ISSUE TITLE
Cant access LongShort Ratio data

### ISSUE THREAD

**Issue by bliss-sid** [binance-exchange/binance-api-postman#23]
When sending request {{url}}/futures/data/topLongShortPositionRatio?symbol=BTCUSDT

I am getting the following error

"error": "Not Found",
"message": "No message available",
"path": "/futures/data/topLongShortPositionRatio"

**Comment by bliss-sid** [comment]
All the request with endpoint /futures/data/ give same error. Do I need to do something different?
Also, the open interest I fetch from the api {{url}}/fapi/v1/openInterest is different from the one displayed on https://www.binance.com/en/futures/funding-history/

**Comment by 2pd** [comment]
{{url}}/futures/data/topLongShortPositionRatio?symbol=BTCUSDT

this endpoint is not available in futures testnet, please try on production env:

 set the `url` in the env to  `https://fapi.binance.com`

**Comment by 2pd** [comment]
for `{url}}/fapi/v1/openInterest` response data format, please refer to

https://binance-docs.github.io/apidocs/futures/en/#open-interest

**Comment by julio899** [comment]
exist socket for this endpoint?

**Comment by 2pd** [comment]
No, I don't think there is websocket stream for this endpoint.
