### ISSUE TITLE
getting 404 error

### ISSUE THREAD

**Issue by roopas89** [binance-exchange/binance-api-postman#46]
Hello I have set all required API key and secrete in postman but still, APIs are giving 404 error
<img width="1041" alt="Screenshot 2020-08-12 at 4 59 51 PM" src="https://user-images.githubusercontent.com/69514227/90010350-55860e80-dcbd-11ea-96d6-56c09441c941.png">
<img width="719" alt="Screenshot 2020-08-12 at 5 00 22 PM" src="https://user-images.githubusercontent.com/69514227/90010384-6171d080-dcbd-11ea-993a-a4e45329be7b.png">

**Comment by 2pd** [comment]
testnet support only with `/api/v3/*` endpoints.
