### ISSUE TITLE
{"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

### ISSUE THREAD

**Issue by bejoyjon** [binance-exchange/binance-api-postman#60]
Noob here. Getting the error {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

Running code from India:
#Importing the 2 libraries required
import time 
import requests

#getting the timestamp
ts = time.time() 

#remaining code generated from Postman using instructions on Binance academy post. 
#The timestamp is adding dynamically ("+str(int(ts))+")
#replacing signature with somesignature in this issue only. My original code has the correct signature
url = "https://api.binance.com/api/v3/account?timestamp="+str(int(ts))+"&signature=somesignature"

payload={}

#replacing api key with somekey in this issue only. My original code has the correct api key. Same for session id.
headers = {
  'Content-Type': 'application/json',
  'X-MBX-APIKEY': 'somekey',
  'Cookie': 'JSESSIONID=somesessionid'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

**Comment by 2pd** [comment]
Most known reason for this is the client's local time is out of sync,  please check it from https://time.is/,  and update your time to be synced. Then it should be fine.

**Comment by bejoyjon** [comment]
Noted. Thanks, Jeremy.

Regards

Bejoy

**Comment by adrianlaraperez88** [comment]
Hi team, i have same issue and my clock is same url have in msg post before

**Comment by 2pd** [comment]
for API concern, please report at dev.binance.vision, unless it's related to postman collection.
